//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindMapApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersFiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersFiles()
        {
            this.UsersLogin = new HashSet<UsersLogin>();
        }
    
        public long id { get; set; }
        public string username { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public bool type { get; set; }
        public System.DateTime createdate { get; set; }
        public bool is_shared { get; set; }
        public string tag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersLogin> UsersLogin { get; set; }
    }
}
